# Generated by Django 5.0.1 on 2024-01-19 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='id_subsection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='tutorials.tutorial_subsection', verbose_name='Подраздел'),
        ),
        migrations.AlterField(
            model_name='tutorial_subsection',
            name='id_tutorial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsections', to='tutorials.tutorial', verbose_name='Раздел'),
        ),
    ]
