# Generated by Django 5.0.1 on 2024-02-02 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0002_alter_article_id_subsection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug_article',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='slug_tutorial',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='tutorial_subsection',
            name='slug_sub_tutorial',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
