# Generated by Django 5.0.1 on 2024-02-02 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0003_article_slug_article_tutorial_slug_tutorial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='short_descr',
            field=models.TextField(max_length=500, verbose_name='Краткое описание'),
        ),
    ]
