# Generated by Django 5.0.1 on 2024-01-09 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.CharField(max_length=100, verbose_name='Вопрос')),
                ('answer', models.CharField(max_length=500, verbose_name='Ответ')),
            ],
            options={
                'verbose_name': 'ЧЗВ',
                'verbose_name_plural': 'ЧЗВ',
                'ordering': ['questions'],
            },
        ),
    ]
