# Generated by Django 5.0.1 on 2024-01-19 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news_article',
            options={'ordering': ['title'], 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterModelOptions(
            name='news_preview',
            options={'ordering': ['title'], 'verbose_name': 'id', 'verbose_name_plural': 'ids'},
        ),
        migrations.AlterField(
            model_name='news_article',
            name='preview',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.news_preview', verbose_name='язык'),
        ),
    ]
